/**
 * @flow
 */

const AppImages: Object = {
  splash: require('../../../Configuration/assets/img_splash.png'),
  app_logo: require('../../../Configuration/assets/app_logo.png'),
  bg_shapes: require('../../../Configuration/assets/bg.png'),
  backRight_blue: require('../../../Configuration/assets/backBlueIcon-1.png'),
  backLeft_blue: require('../../../Configuration/assets/backBlueIcon.png'),
  backRight_white: require('../../../Configuration/assets/backligthicon-1.png'),
  backLeft_white: require('../../../Configuration/assets/backligthicon.png'),
  slider1: require('../../../Configuration/assets/quranapp-icons-slider-1.png'),
  slider2: require('../../../Configuration/assets/quranapp-icons-slider-2.png'),
  slider3: require('../../../Configuration/assets/quranapp-icons-slider-3.png'),
  slider4: require('../../../Configuration/assets/quranapp-icons-slider-4.png'),
  edit_icon: require('../../../Configuration/assets/edit.png'),
  arrow_down: require('../../../Configuration/assets/arrow-down.png'),
  reciterTest: require('../../../Configuration/assets/NoPath.png'),
  search_icon: require('../../../Configuration/assets/ic_search_24px.png'),
  main_icon: require('../../../Configuration/assets/Group33.png'),
  test_icon: require('../../../Configuration/assets/New-Message-Icon.png'),
  search_tab_icon: require('../../../Configuration/assets/Group-12.png'),
  about_icon: require('../../../Configuration/assets/Icons-Top-Bar-Info.png'),
  setting_icon: require('../../../Configuration/assets/ic_settings_24px.png'),
  testing_icon: require('../../../Configuration/assets/Group31.png'),
  coloring_icon: require('../../../Configuration/assets/ic_brush_24px.png'),
  memoring_icon: require('../../../Configuration/assets/ic_check_24px.png'),
  playing_icon: require('../../../Configuration/assets/play.png'),
  tafsering_icon: require('../../../Configuration/assets/tafser.png'),
  repetitions: require('../../../Configuration/assets/repetitions.png'),
  interval: require('../../../Configuration/assets/interval.png'),
  download: require('../../../Configuration/assets/download.png'),
  close: require('../../../Configuration/assets/ic_close_24px.png'),
  tafser: require('../../../Configuration/assets/tfser.png'),
  setting: require('../../../Configuration/assets/white_setting.png'),
  white_mark: require('../../../Configuration/assets/white_mark.png'),
  checked: require('../../../Configuration/assets/checkbox-selected.png'),
  unchecked: require('../../../Configuration/assets/Ellipse1.png'),
  details: require('../../../Configuration/assets/clear-icon.png'),
  black_mark: require('../../../Configuration/assets/blackmark.png'),
  unfill_mark: require('../../../Configuration/assets/mark-notmarked.png'),
  share: require('../../../Configuration/assets/share-icon.png'),
  unselect_star: require('../../../Configuration/assets/star-notselected.png'),
  select_star: require('../../../Configuration/assets/star-selected.png'),
  gray_close_icon: require('../../../Configuration/assets/ic_cancel_24px.png'),
  sending: require('../../../Configuration/assets/sending.png'),
  red_record: require('../../../Configuration/assets/redRecord.png'),
  profile: require('../../../Configuration/assets/profile.png'),
  arrowRight: require('../../../Configuration/assets/arrow-rigth.png'),
  arrowLeft: require('../../../Configuration/assets/arrow-rigth-1.png'),
  green_mic: require('../../../Configuration/assets/ic_mic_24px.png'),
};

export default AppImages;
